/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.playcar.view;

import br.com.playcar.dao.AgendamentoDAO;
import br.com.playcar.dao.CarrosDAO;
import br.com.playcar.dao.ClienteDAO;
import br.com.playcar.dao.EnderecoDAO;
import br.com.playcar.dao.FuncionarioDAO;
import br.com.playcar.model.Agendamento;
import br.com.playcar.model.Carros;
import br.com.playcar.model.Cliente;
import br.com.playcar.model.Endereco;
import br.com.playcar.model.Funcionario;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.playcar.model.Utilitarios;

/**
 *
 * @author freddy
 */
public class FRagendamento extends javax.swing.JFrame {

    /**
     * Creates new form FRagendamento
     */
    public FRagendamento() {
        initComponents();
    }

    public void listarcarros(int id) {
        txtCarro.removeAllItems();

        try {

            CarrosDAO dao = new CarrosDAO();
            List<Carros> lista = dao.buscarPorCarros(id);
            for (Carros f : lista) {
                txtCarro.addItem("marca: " + f.getMarca() + ", " + "modelo: " + f.getModelo() + ", " + "placa: " + f.getPlaca());

            }

        } catch (Exception e) {
        }
    }

    public void listarenderecos(int id) {
        try {

            txtEndereco.removeAllItems();
            EnderecoDAO dao = new EnderecoDAO();
            List<Endereco> lista = dao.buscarPorCliente(id);
            for (Endereco f : lista) {
                txtEndereco.addItem("rua: " + f.getRua() + ", " + "número: " + f.getNumero() + ", " + "bairro: " + f.getBairro());
            }

        } catch (Exception e) {
        }

    }

    public void listafuncionarios() {
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            List<Funcionario> lista = dao.buscarFuncionarios();
            txtResponsavel.removeAllItems();
            for (Funcionario f : lista) {
                txtResponsavel.addItem(f.getNome());
            }
        } catch (Exception e) {
        }
    }

    public void listarAgendamento(int id) {
        try {
            AgendamentoDAO dao = new AgendamentoDAO();
            List<Agendamento> lista = dao.buscarPorNome(id);
            DefaultTableModel dados = (DefaultTableModel) tabelapornome.getModel();
            dados.setNumRows(0);

            SimpleDateFormat formatador = new SimpleDateFormat("dd-MM-yyyy");

            for (Agendamento f : lista) {
                dados.addRow(new Object[]{
                    f.getData_agendamento(),
                    f.getCarro_id(),
                    f.getBuscar(),
                    f.getEndereco_id(),
                    f.getTipo(),
                    f.getResponsavel_id()
                });
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        testetabela = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtTipo = new javax.swing.JComboBox<>();
        txtCarro = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JComboBox<>();
        txtResponsavel = new javax.swing.JComboBox<>();
        campoData = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txtbuscarnome = new javax.swing.JTextField();
        btnnovo3 = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        DataBuscar = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDada = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtnomebuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelapornome = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        testetabela1 = new javax.swing.JTable();
        txtBusscar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        label1.setFont(new java.awt.Font("Liberation Serif", 0, 50)); // NOI18N
        label1.setText("Playcar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Funcinário Responsável:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Buscar Cliente:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("Carro:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("Data de Agendamento:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel5.setText("Precisa buscar:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("Endereço:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel7.setText("Tipo de lavagem:");

        testetabela.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        testetabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testetabela.setRowHeight(36);
        testetabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testetabelaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(testetabela);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel8.setText("Cliente:");

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        txtTipo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semi", "Completa", "Premium" }));
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        txtCarro.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarroActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        txtEndereco.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        txtResponsavel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtResponsavel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtResponsavelItemStateChanged(evt);
            }
        });
        txtResponsavel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtResponsavelMouseClicked(evt);
            }
        });
        txtResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResponsavelActionPerformed(evt);
            }
        });

        campoData.setDateFormatString("dd/MM/y");
        campoData.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        campoData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoDataMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton1.setText("Adicionar Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtbuscarnome.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtbuscarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarnomeActionPerformed(evt);
            }
        });

        btnnovo3.setText("NOVO");
        btnnovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovo3ActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnexcluir.setText("EXCLUIR");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel11.setText("ID Cliente:");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel12.setText("ID Agendamento:");

        txtID1.setEditable(false);
        txtID1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtbuscarnome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtResponsavel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCarro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(btnnovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtbuscarnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Agendamento", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        DataBuscar.setDateFormatString("dd/MM/y");
        DataBuscar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        DataBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataBuscarMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel9.setText("Data de Agendamento:");

        btnBuscarData.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btnBuscarData.setText("Buscar");
        btnBuscarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDataActionPerformed(evt);
            }
        });

        tabelaDada.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        tabelaDada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Carro", "Buscar", "Endereço", "Tipo de Lavagem", "Responsável", "ID do Cliente", "ID do Agendamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDada.setRowHeight(36);
        tabelaDada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDadaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDada);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnBuscarData))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(DataBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarData))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar por Data", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel10.setText("Cliente:");

        txtnomebuscar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtnomebuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomebuscarActionPerformed(evt);
            }
        });

        tabelapornome.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tabelapornome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Carro", "Buscar", "Endereço", "Tipo de Lavagem", "Responsável"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelapornome.setRowHeight(36);
        jScrollPane2.setViewportView(tabelapornome);
        if (tabelapornome.getColumnModel().getColumnCount() > 0) {
            tabelapornome.getColumnModel().getColumn(0).setHeaderValue("Data");
            tabelapornome.getColumnModel().getColumn(1).setHeaderValue("Carro");
            tabelapornome.getColumnModel().getColumn(2).setHeaderValue("Buscar");
            tabelapornome.getColumnModel().getColumn(3).setHeaderValue("Endereço");
            tabelapornome.getColumnModel().getColumn(4).setHeaderValue("Tipo de Lavagem");
            tabelapornome.getColumnModel().getColumn(5).setHeaderValue("Responsável");
        }

        testetabela1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        testetabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testetabela1.setRowHeight(36);
        testetabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testetabela1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(testetabela1);

        txtBusscar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtBusscar.setText("Buscar");
        txtBusscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtnomebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(txtBusscar)))
                        .addGap(476, 476, 476)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnomebuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusscar)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar por Cliente", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void testetabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testetabelaMouseClicked
        // TODO add your handling code here:
        txtCliente.setText(testetabela.getValueAt(testetabela.getSelectedRow(), 1).toString());
        txtID.setText(testetabela.getValueAt(testetabela.getSelectedRow(), 0).toString());
        int id = (int) testetabela.getValueAt(testetabela.getSelectedRow(), 0);
        listarcarros(id);
        listarenderecos(id);
        listafuncionarios();

    }//GEN-LAST:event_testetabelaMouseClicked

    private void campoDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDataMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_campoDataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Date data = campoData.getDate();

            SimpleDateFormat formatador = new SimpleDateFormat("dd-MM-yyyy");

            String dataFormatada = formatador.format(data);
            JOptionPane.showMessageDialog(null, "Data adicionada com sucesso");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao adicionar data");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbuscarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarnomeActionPerformed

        String nome = "%" + txtbuscarnome.getText() + "%";
        ClienteDAO teste = new ClienteDAO();
        List<Cliente> listadeclientes = teste.buscarporClienteNome(nome);

        DefaultTableModel dados = (DefaultTableModel) testetabela.getModel();

        dados.setNumRows(0);
        for (Cliente c : listadeclientes) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),});
        }
    }//GEN-LAST:event_txtbuscarnomeActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCarroActionPerformed

    private void txtResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResponsavelActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtResponsavelActionPerformed

    private void txtResponsavelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtResponsavelMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtResponsavelMouseClicked

    private void txtResponsavelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtResponsavelItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtResponsavelItemStateChanged

    private void btnnovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovo3ActionPerformed
        // TODO add your handling code here:
        new Utilitarios().LimparTela(jPanel2);

        campoData.setDate(null);
        txtTipo.setSelectedItem("Semi");
        txtCarro.setSelectedItem(null);
        txtBuscar.setSelectedItem("Não");
        txtEndereco.setSelectedItem(null);
        txtResponsavel.setSelectedItem(null);
        DefaultTableModel dados = (DefaultTableModel) testetabela.getModel();
        dados.setNumRows(0);

    }//GEN-LAST:event_btnnovo3ActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:

        try {
            Date data = campoData.getDate();

            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");

            String dataFormatada = formatador.format(data);
            Agendamento obj = new Agendamento();

            obj.setData_agendamento(dataFormatada);
            obj.setTipo(txtTipo.getSelectedItem().toString());
            obj.setCliente_id(Integer.parseInt(txtID.getText()));
            obj.setCarro_id(txtCarro.getSelectedItem().toString());
            obj.setBuscar(txtBuscar.getSelectedItem().toString());
            obj.setEndereco_id(txtEndereco.getSelectedItem().toString());
            obj.setResponsavel_id(txtResponsavel.getSelectedItem().toString());
            obj.setNomeCliente(txtCliente.getText());
            AgendamentoDAO dao = new AgendamentoDAO();
            dao.cadastrarAgendamento(obj);
            new Utilitarios().LimparTela(jPanel2);

            campoData.setDate(null);
            txtTipo.setSelectedItem("Semi");
            txtCarro.setSelectedItem(null);
            txtBuscar.setSelectedItem("Não");
            txtEndereco.setSelectedItem(null);
            txtResponsavel.setSelectedItem(null);
            DefaultTableModel dados = (DefaultTableModel) testetabela.getModel();
            dados.setNumRows(0);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        try {
            Date data = campoData.getDate();
            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
            String dataFormatada = formatador.format(data);

            Agendamento obj = new Agendamento();
            obj.setId(Integer.parseInt(txtID1.getText()));
            obj.setData_agendamento(dataFormatada);
            obj.setTipo(txtTipo.getSelectedItem().toString());
            obj.setCliente_id(Integer.parseInt(txtID.getText()));
            obj.setCarro_id(txtCarro.getSelectedItem().toString());
            obj.setBuscar(txtBuscar.getSelectedItem().toString());
            obj.setEndereco_id(txtEndereco.getSelectedItem().toString());
            obj.setResponsavel_id(txtResponsavel.getSelectedItem().toString());
            obj.setNomeCliente(txtCliente.getText());

            AgendamentoDAO dao = new AgendamentoDAO();
            dao.editarAgentamento(obj);
            new Utilitarios().LimparTela(jPanel2);

            campoData.setDate(null);
            txtTipo.setSelectedItem("Semi");
            txtCarro.setSelectedItem(null);
            txtBuscar.setSelectedItem("Não");
            txtEndereco.setSelectedItem(null);
            txtResponsavel.setSelectedItem(null);
            DefaultTableModel dados = (DefaultTableModel) testetabela.getModel();
            dados.setNumRows(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // TODO add your handling code here:
        String id = txtID1.getText();
        AgendamentoDAO dao = new AgendamentoDAO();
        dao.excluirAgendamento(Integer.parseInt(id));
        new Utilitarios().LimparTela(jPanel2);
        campoData.setDate(null);
        txtTipo.setSelectedItem("Semi");
        txtCarro.setSelectedItem(null);
        txtBuscar.setSelectedItem("Não");
        txtEndereco.setSelectedItem(null);
        txtResponsavel.setSelectedItem(null);
        DefaultTableModel dados = (DefaultTableModel) testetabela.getModel();
        dados.setNumRows(0);
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void DataBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DataBuscarMouseClicked

    private void btnBuscarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDataActionPerformed
        // TODO add your handling code here:
        Date data = DataBuscar.getDate();

        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = formatador.format(data);
        AgendamentoDAO dao = new AgendamentoDAO();

        List<Agendamento> lista = dao.buscarPordata(dataFormatada);
        DefaultTableModel dados = (DefaultTableModel) tabelaDada.getModel();
        dados.setNumRows(0);

        for (Agendamento c : lista) {
            dados.addRow(new Object[]{
                c.getNomeCliente(),
                c.getCarro_id(),
                c.getBuscar(),
                c.getEndereco_id(),
                c.getTipo(),
                c.getResponsavel_id(),
                c.getCliente_id(),
                c.getId(),});
        }

    }//GEN-LAST:event_btnBuscarDataActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void testetabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testetabela1MouseClicked
        // TODO add your handling code here:
        int id = (int) testetabela1.getValueAt(testetabela1.getSelectedRow(), 0);

        listarAgendamento(id);

    }//GEN-LAST:event_testetabela1MouseClicked

    private void txtnomebuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomebuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomebuscarActionPerformed

    private void txtBusscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusscarActionPerformed
        // TODO add your handling code here:
        String nome = "%" + txtnomebuscar.getText() + "%";
        ClienteDAO teste = new ClienteDAO();
        List<Cliente> listadeclientes = teste.buscarporClienteNome(nome);
        DefaultTableModel dados = (DefaultTableModel) testetabela1.getModel();

        dados.setNumRows(0);
        for (Cliente c : listadeclientes) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),});
        }
    }//GEN-LAST:event_txtBusscarActionPerformed

    private void tabelaDadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDadaMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        campoData.setCalendar(DataBuscar.getCalendar());
        txtTipo.setSelectedItem(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 4));
        txtCliente.setText(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 0).toString());
        txtCarro.removeAllItems();
        txtCarro.addItem(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 1).toString());
        txtBuscar.setSelectedItem(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 2));
        txtEndereco.removeAllItems();
        txtEndereco.addItem((String) tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 3));
        txtResponsavel.removeAllItems();
        txtResponsavel.addItem(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 5).toString());
        txtID1.setText(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 7).toString());
        txtID.setText(tabelaDada.getValueAt(tabelaDada.getSelectedRow(), 6).toString());

    }//GEN-LAST:event_tabelaDadaMouseClicked

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRagendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRagendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRagendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRagendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRagendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataBuscar;
    private javax.swing.JButton btnBuscarData;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo3;
    private javax.swing.JButton btnsalvar;
    private com.toedter.calendar.JDateChooser campoData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tabelaDada;
    private javax.swing.JTable tabelapornome;
    public javax.swing.JTable testetabela;
    public javax.swing.JTable testetabela1;
    private javax.swing.JComboBox<String> txtBuscar;
    private javax.swing.JButton txtBusscar;
    public javax.swing.JComboBox<String> txtCarro;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JComboBox<String> txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JComboBox<String> txtResponsavel;
    private javax.swing.JComboBox<String> txtTipo;
    private javax.swing.JTextField txtbuscarnome;
    private javax.swing.JTextField txtnomebuscar;
    // End of variables declaration//GEN-END:variables

    private String toString(int id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
