/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.playcar.view;

import br.com.playcar.dao.CarrosDAO;
import br.com.playcar.dao.ClienteDAO;
import br.com.playcar.dao.EnderecoDAO;
import br.com.playcar.model.Carros;
import br.com.playcar.model.Cliente;
import br.com.playcar.model.Endereco;
import br.com.playcar.model.Utilitarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author freddy
 */
public class FRcliente extends javax.swing.JFrame {

    /**
     * Creates new form FRcliente
     */
    //metodo listar endereços
    public void listarenderecos(int id) {
        try {

            EnderecoDAO dao = new EnderecoDAO();
            List<Endereco> lista = dao.buscarPorCliente(id);
            DefaultTableModel dados = (DefaultTableModel) TabelaEnderecos1.getModel();
            dados.setNumRows(0);

            for (Endereco c : lista) {
                dados.addRow(new Object[]{
                    c.getId(),
                    c.getTipo_endereco(),
                    c.getRua(),
                    c.getNumero(),
                    c.getBairro(),
                    c.getComplemento(),
                    c.getCep()
                });
            }
        } catch (Exception e) {
        }

    }

    public void listarcarros(int id) {
        try {

            CarrosDAO dao = new CarrosDAO();
            List<Carros> lista = dao.buscarPorCarros(id);
            DefaultTableModel dados = (DefaultTableModel) tabelacarros.getModel();
            dados.setNumRows(0);

            for (Carros c : lista) {
                dados.addRow(new Object[]{
                    c.getId(),
                    c.getMarca(),
                    c.getModelo(),
                    c.getCor(),
                    c.getPlaca()

                });
            }
        } catch (Exception e) {
        }

    }

    public FRcliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        telaClientes = new javax.swing.JTabbedPane();
        dados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txttelefone = new javax.swing.JFormattedTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        btnsalvar = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        endereco = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtcomplemento = new javax.swing.JTextField();
        txtrua = new javax.swing.JTextField();
        txtcep = new javax.swing.JFormattedTextField();
        selecttipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnSalvarEndereco = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtbuscarnome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testetabela = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtClienteachado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        selectmarca = new javax.swing.JComboBox<>();
        btnnovo1 = new javax.swing.JButton();
        btnnovo2 = new javax.swing.JButton();
        btnnovo3 = new javax.swing.JButton();
        btnnovo4 = new javax.swing.JButton();
        txtbuscarnome1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        testetabela1 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtClienteachado1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaEnderecos1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelacarros = new javax.swing.JTable();
        txtbuscarnome2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        testetabela2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtClienteachado2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        label1.setFont(new java.awt.Font("Liberation Serif", 0, 50)); // NOI18N
        label1.setText("Playcar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1554, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        telaClientes.setBackground(new java.awt.Color(255, 255, 255));
        telaClientes.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        dados.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("Telefone:");

        txtcodigo.setEditable(false);
        txtcodigo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        txtnome.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        try {
            txttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttelefone.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnnovo.setText("NOVO");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btneditar.setText("EDITAR");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnexcluir.setText("EXCLUIR");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dadosLayout = new javax.swing.GroupLayout(dados);
        dados.setLayout(dadosLayout);
        dadosLayout.setHorizontalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosLayout.createSequentialGroup()
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        dadosLayout.setVerticalGroup(
            dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(99, 99, 99)
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(txttelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addGroup(dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        telaClientes.addTab("Dados Pessoais", dados);

        endereco.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("Tipo:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel7.setText("Rua:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel8.setText("Número:");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel9.setText("Bairro:");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel10.setText("Complemento:");

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel11.setText("CEP:");

        txtnumero.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        txtbairro.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbairroActionPerformed(evt);
            }
        });

        txtcomplemento.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        txtrua.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcep.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcepActionPerformed(evt);
            }
        });

        selecttipo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        selecttipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "casa", "apartamento", "condominio", "trabalho" }));
        selecttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecttipoActionPerformed(evt);
            }
        });

        jButton1.setText("NOVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalvarEndereco.setText("SALVAR");
        btnSalvarEndereco.setPreferredSize(new java.awt.Dimension(73, 24));
        btnSalvarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEnderecoActionPerformed(evt);
            }
        });

        jButton3.setText("EDITAR");
        jButton3.setPreferredSize(new java.awt.Dimension(73, 24));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("EXCLUIR");
        jButton4.setPreferredSize(new java.awt.Dimension(73, 24));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtbuscarnome.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtbuscarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarnomeActionPerformed(evt);
            }
        });

        testetabela.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        testetabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testetabela.setRowHeight(36);
        testetabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testetabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(testetabela);

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel12.setText("Buscar por Cliente:");

        txtClienteachado.setEditable(false);
        txtClienteachado.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtClienteachado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteachadoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel19.setText("Cliente:");

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel22.setText("ID:");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        javax.swing.GroupLayout enderecoLayout = new javax.swing.GroupLayout(endereco);
        endereco.setLayout(enderecoLayout);
        enderecoLayout.setHorizontalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enderecoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbuscarnome, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteachado, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(enderecoLayout.createSequentialGroup()
                                .addComponent(selecttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(enderecoLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnSalvarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        enderecoLayout.setVerticalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteachado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selecttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        telaClientes.addTab("Endereços", endereco);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel14.setText("Cliente:");

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel15.setText("Marca:");

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel16.setText("Modelo:");

        txtmodelo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel17.setText("Cor:");

        txtcor.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel18.setText("Placa:");

        txtplaca.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        selectmarca.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        selectmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audi", "BMW", "BYD", "CAOA Chery", "Chevrolet", "Citroen", "Fiat", "Ford", "Haval", "Honda", "Hyndai", "Iveco", "JAC", "Jeep", "Kia", "Land Rover", "Lexus", "Mercedes-Benz", "Mini", "Mitsubishi", "Nissan", "Peugeot", "Porsche", "Ram", "Renault", "Subaru", "Suzuki", "Toyota", "Volkswagen", "Volvo", "Outros" }));
        selectmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectmarcaActionPerformed(evt);
            }
        });

        btnnovo1.setText("NOVO");
        btnnovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovo1ActionPerformed(evt);
            }
        });

        btnnovo2.setText("EDITAR");
        btnnovo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovo2ActionPerformed(evt);
            }
        });

        btnnovo3.setText("SALVAR");
        btnnovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovo3ActionPerformed(evt);
            }
        });

        btnnovo4.setText("EXCLUIR");
        btnnovo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovo4ActionPerformed(evt);
            }
        });

        txtbuscarnome1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtbuscarnome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarnome1ActionPerformed(evt);
            }
        });

        testetabela1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        testetabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testetabela1.setRowHeight(36);
        testetabela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testetabela1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(testetabela1);

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel20.setText("Buscar por Cliente:");

        txtClienteachado1.setEditable(false);
        txtClienteachado1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtClienteachado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteachado1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel23.setText("ID:");

        txtID1.setEditable(false);
        txtID1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbuscarnome1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtplaca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtClienteachado1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(btnnovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnnovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnnovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(btnnovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarnome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteachado1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(selectmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(txtcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(txtplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnovo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnovo2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        telaClientes.addTab("Carros", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        TabelaEnderecos1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        TabelaEnderecos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Rua", "Número", "Bairro", "Complemento", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEnderecos1.setRowHeight(40);
        TabelaEnderecos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEnderecos1MouseClicked(evt);
            }
        });
        TabelaEnderecos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaEnderecos1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaEnderecos1);

        tabelacarros.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        tabelacarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Modelo", "Cor", "Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelacarros.setRowHeight(40);
        tabelacarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelacarrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelacarros);

        txtbuscarnome2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtbuscarnome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarnome2ActionPerformed(evt);
            }
        });

        testetabela2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        testetabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "nome", "CPF", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        testetabela2.setRowHeight(36);
        testetabela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testetabela2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                testetabela2MouseEntered(evt);
            }
        });
        jScrollPane5.setViewportView(testetabela2);

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel13.setText("Buscar por Cliente:");

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel21.setText("Cliente:");

        txtClienteachado2.setEditable(false);
        txtClienteachado2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        txtClienteachado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteachado2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton2.setText("Editar Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbuscarnome2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtClienteachado2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(657, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarnome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteachado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        telaClientes.addTab("Buscar Cliente", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 1763, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        try {
            Cliente obj = new Cliente();
            obj.setNome(txtnome.getText());
            obj.setCpf(txtcpf.getText());
            obj.setTelefone(txttelefone.getText());
            ClienteDAO dao = new ClienteDAO();
            dao.cadastrarCliente(obj);
            new Utilitarios().LimparTela(dados);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        Cliente obj = new Cliente();
        obj.setId(Integer.parseInt(txtcodigo.getText()));
        obj.setNome(txtnome.getText());
        obj.setCpf(txtcpf.getText());
        obj.setTelefone(txttelefone.getText());
        ClienteDAO dao = new ClienteDAO();
        dao.editarCliente(obj);
        new Utilitarios().LimparTela(dados);

    }//GEN-LAST:event_btneditarActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        // TODO add your handling code here:
        String id = txtcodigo.getText();
        ClienteDAO dao = new ClienteDAO();
        dao.excluirCliente(Integer.parseInt(id));
        new Utilitarios().LimparTela(dados);
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed
        // TODO add your handling code here:
        new Utilitarios().LimparTela(dados);
    }//GEN-LAST:event_btnnovoActionPerformed

    private void selecttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecttipoActionPerformed

    private void txtcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcepActionPerformed

    private void txtbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbairroActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btnSalvarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEnderecoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            Endereco obj = new Endereco();
            obj.setCliente_id((int) testetabela.getValueAt(testetabela.getSelectedRow(), 0));

            obj.setTipo_endereco(selecttipo.getSelectedItem().toString());
            obj.setRua(txtrua.getText());
            obj.setNumero(txtnumero.getText());
            obj.setBairro(txtbairro.getText());
            obj.setComplemento(txtcomplemento.getText());
            obj.setCep(txtcep.getText());

            EnderecoDAO dao = new EnderecoDAO();
            dao.cadastrarEnderecos(obj);

            new Utilitarios().LimparTela(endereco);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSalvarEnderecoActionPerformed

    private void btnnovo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovo4ActionPerformed
        // TODO add your handling code here:
        String id = txtID1.getText();
        CarrosDAO dao = new CarrosDAO();
        dao.excluirCarro(Integer.parseInt(id));
        new Utilitarios().LimparTela(jPanel4);
        selectmarca.setSelectedItem("Audi");
        DefaultTableModel dados = (DefaultTableModel) testetabela1.getModel();

        dados.setNumRows(0);

    }//GEN-LAST:event_btnnovo4ActionPerformed

    private void btnnovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovo3ActionPerformed
        // TODO add your handling code here:
        try {

            Carros obj = new Carros();
            obj.setCliente_id((int) testetabela1.getValueAt(testetabela1.getSelectedRow(), 0));

            obj.setMarca(selectmarca.getSelectedItem().toString());
            obj.setModelo(txtmodelo.getText());
            obj.setModelo(txtmodelo.getText());
            obj.setCor(txtcor.getText());
            obj.setPlaca(txtplaca.getText());

            CarrosDAO dao = new CarrosDAO();
            dao.cadastrarCarro(obj);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnnovo3ActionPerformed

    private void btnnovo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovo2ActionPerformed
        // TODO add your handling code here:
        Carros obj = new Carros();
        obj.setMarca(selectmarca.getSelectedItem().toString());
        obj.setModelo(txtmodelo.getText());
        obj.setCor(txtcor.getText());
        obj.setPlaca(txtplaca.getText());
        obj.setId(Integer.parseInt(txtID1.getText()));
        CarrosDAO dao = new CarrosDAO();
        dao.editarCarro(obj);
        new Utilitarios().LimparTela(jPanel4);
        selectmarca.setSelectedItem("Audi");
        
    }//GEN-LAST:event_btnnovo2ActionPerformed

    private void btnnovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovo1ActionPerformed
        // TODO add your handling code here:
        new Utilitarios().LimparTela(jPanel4);
        selectmarca.setSelectedItem("Audi");
    }//GEN-LAST:event_btnnovo1ActionPerformed

    private void selectmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectmarcaActionPerformed

    private void txtbuscarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarnomeActionPerformed

        String nome = "%" + txtbuscarnome.getText() + "%";
        ClienteDAO teste = new ClienteDAO();
        List<Cliente> listadeclientes = teste.buscarporClienteNome(nome);

        DefaultTableModel dados = (DefaultTableModel) testetabela.getModel();

        dados.setNumRows(0);
        for (Cliente c : listadeclientes) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),});
        }
    }//GEN-LAST:event_txtbuscarnomeActionPerformed

    private void testetabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testetabelaMouseClicked
        // TODO add your handling code here:

        txtClienteachado.setText(testetabela.getValueAt(testetabela.getSelectedRow(), 1).toString());

    }//GEN-LAST:event_testetabelaMouseClicked

    private void txtClienteachadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteachadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtClienteachadoActionPerformed

    private void txtbuscarnome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarnome1ActionPerformed
        // TODO add your handling code here:
        String nome = "%" + txtbuscarnome1.getText() + "%";
        ClienteDAO teste = new ClienteDAO();
        List<Cliente> listadeclientes = teste.buscarporClienteNome(nome);

        DefaultTableModel dados = (DefaultTableModel) testetabela1.getModel();

        dados.setNumRows(0);
        for (Cliente c : listadeclientes) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),});
        }
    }//GEN-LAST:event_txtbuscarnome1ActionPerformed

    private void testetabela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testetabela1MouseClicked
        // TODO add your handling code here:
        txtClienteachado1.setText(testetabela1.getValueAt(testetabela1.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_testetabela1MouseClicked

    private void txtClienteachado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteachado1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtClienteachado1ActionPerformed

    private void txtbuscarnome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarnome2ActionPerformed
        // TODO add your handling code here:
        String nome = "%" + txtbuscarnome2.getText() + "%";
        ClienteDAO teste = new ClienteDAO();
        List<Cliente> listadeclientes = teste.buscarporClienteNome(nome);

        DefaultTableModel dados = (DefaultTableModel) testetabela2.getModel();

        dados.setNumRows(0);
        for (Cliente c : listadeclientes) {
            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getTelefone()
            });
        }
    }//GEN-LAST:event_txtbuscarnome2ActionPerformed

    private void testetabela2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testetabela2MouseClicked
        // TODO add your handling code here:
        txtClienteachado2.setText(testetabela2.getValueAt(testetabela2.getSelectedRow(), 1).toString());
        int id = (int) testetabela2.getValueAt(testetabela2.getSelectedRow(), 0);
        listarenderecos(id);
        listarcarros(id);

    }//GEN-LAST:event_testetabela2MouseClicked

    private void txtClienteachado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteachado2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtClienteachado2ActionPerformed

    private void testetabela2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testetabela2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_testetabela2MouseEntered

    private void TabelaEnderecos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEnderecos1MouseClicked
        // TODO add your handling code here:
        telaClientes.setSelectedIndex(1);
        txtbuscarnome.setText(txtClienteachado2.getText());
        txtID.setText(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 0).toString());
        selecttipo.setSelectedItem(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 1));
        txtnumero.setText(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 3).toString());
        txtrua.setText(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 2).toString());
        txtbairro.setText(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 4).toString());
        txtcomplemento.setText(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 5).toString());
        txtcep.setText(TabelaEnderecos1.getValueAt(TabelaEnderecos1.getSelectedRow(), 6).toString());
        DefaultTableModel dados = (DefaultTableModel) TabelaEnderecos1.getModel();

        dados.setNumRows(0);
    }//GEN-LAST:event_TabelaEnderecos1MouseClicked

    private void TabelaEnderecos1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaEnderecos1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaEnderecos1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int id = (int) testetabela.getValueAt(testetabela.getSelectedRow(), 0);
        EnderecoDAO dao = new EnderecoDAO();
        dao.excluirEndereco(id);
        new Utilitarios().LimparTela(endereco);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Endereco obj = new Endereco();
        obj.setTipo_endereco(selecttipo.getSelectedItem().toString());
        obj.setRua(txtrua.getText());
        obj.setNumero(txtnumero.getText());
        obj.setBairro(txtbairro.getText());
        obj.setComplemento(txtcomplemento.getText());
        obj.setCep(txtcep.getText());
        obj.setId(Integer.parseInt(txtID.getText()));

        EnderecoDAO dao = new EnderecoDAO();
        dao.alterarEndereco(obj);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Utilitarios().LimparTela(endereco);
        selecttipo.setSelectedItem("casa");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        telaClientes.setSelectedIndex(0);
        txtcodigo.setText(testetabela2.getValueAt(testetabela2.getSelectedRow(), 0).toString());
        txtnome.setText(testetabela2.getValueAt(testetabela2.getSelectedRow(), 1).toString());
        txtcpf.setText(testetabela2.getValueAt(testetabela2.getSelectedRow(), 2).toString());
        txttelefone.setText(testetabela2.getValueAt(testetabela2.getSelectedRow(), 3).toString());
        DefaultTableModel dados = (DefaultTableModel) testetabela2.getModel();
        dados.setNumRows(0);
        txtbuscarnome2.setText("");
        txtClienteachado2.setText("");
        DefaultTableModel dados1 = (DefaultTableModel) tabelacarros.getModel();
        dados1.setNumRows(0);
        DefaultTableModel dados2 = (DefaultTableModel) TabelaEnderecos1.getModel();
        dados2.setNumRows(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelacarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelacarrosMouseClicked
        // TODO add your handling code here:
        telaClientes.setSelectedIndex(2);
        txtbuscarnome1.setText(txtClienteachado2.getText());
        txtID1.setText(tabelacarros.getValueAt(tabelacarros.getSelectedRow(), 0).toString());
        selectmarca.setSelectedItem(tabelacarros.getValueAt(tabelacarros.getSelectedRow(), 1));
        txtmodelo.setText(tabelacarros.getValueAt(tabelacarros.getSelectedRow(), 2).toString());
        txtcor.setText(tabelacarros.getValueAt(tabelacarros.getSelectedRow(), 3).toString());
        txtplaca.setText(tabelacarros.getValueAt(tabelacarros.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tabelacarrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TabelaEnderecos1;
    private javax.swing.JButton btnSalvarEndereco;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnnovo1;
    private javax.swing.JButton btnnovo2;
    private javax.swing.JButton btnnovo3;
    private javax.swing.JButton btnnovo4;
    private javax.swing.JButton btnsalvar;
    public javax.swing.JPanel dados;
    public javax.swing.JPanel endereco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private javax.swing.JComboBox<String> selectmarca;
    private javax.swing.JComboBox<String> selecttipo;
    public javax.swing.JTable tabelacarros;
    public javax.swing.JTabbedPane telaClientes;
    private javax.swing.JTable testetabela;
    public javax.swing.JTable testetabela1;
    public javax.swing.JTable testetabela2;
    private javax.swing.JTextField txtClienteachado;
    private javax.swing.JTextField txtClienteachado1;
    private javax.swing.JTextField txtClienteachado2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtbuscarnome;
    private javax.swing.JTextField txtbuscarnome1;
    private javax.swing.JTextField txtbuscarnome2;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txtcor;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtrua;
    private javax.swing.JFormattedTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
